name: CI

on:
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "npm"

    - name: Install dependencies
      run: npm ci

    - name: Lint
      uses: github/super-linter@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: main
        LINTER_RULES_PATH: /
        FILTER_REGEX_INCLUDE: .*src/.*
        TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.cjs

