name: CI

on:
  pull_request: null
  push:
    branches:
      - "main"

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    if: github.event_name == 'pull_request'
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "npm"

    - name: Install dependencies
      run: npm ci

    - name: Lint
      uses: github/super-linter@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: main
        LINTER_RULES_PATH: /
        FILTER_REGEX_INCLUDE: .*/src/.*
        TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.cjs
        JAVASCRIPT_DEFAULT_STYLE: prettier
        TYPESCRIPT_DEFAULT_STYLE: prettier
        VALIDATE_CSS: true
        VALIDATE_GITLEAKS: true
        VALIDATE_HTML: true
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_JSX: true
        VALIDATE_TSX: true
        VALIDATE_TYPESCRIPT_ES: true

  tsc:
    if: github.event_name == 'pull_request'
    name: Typecheck (tsc)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "npm"

    - name: Install dependencies
      run: npm ci

    - name: Run tsc
      run: npm run tsc

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "npm"

    - name: Install dependencies
      run: npm ci

    - name: Set Sentry Release (PR)
      if: ${{ github.event_name == 'pull_request' }}
      run: echo "SENTRY_RELEASE=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}

    - name: Setup Sentry Release (Push)
      if: ${{ github.event_name == 'push' }}
      run: echo "SENTRY_RELEASE=${GITHUB_SHA}" >> ${GITHUB_ENV}

    - name: Build
      run: npm run build -- --public-url "https://mozilla.github.io/limelight/"
      env:
        SENTRY_DSN: "https://ee81b39e144b4223b6b0b93ac7b093ae@o1069899.ingest.sentry.io/4504371030327296"

    - name: Upload Artifact
      if: github.event_name == 'push'
      uses: actions/upload-pages-artifact@v1
      with:
        path: "dist"

  deploy:
    name: Deploy
    if: github.event_name == 'push'
    needs:
      - "build"
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        id: deployment
